version: 2 # use CircleCI 2.0
jobs: # basic units of work in a run
  test: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: golang:1.13-alpine

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - run:
          name: Run unit tests

          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            go test -v ./...

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results
  build: # runs not using Workflows must have a `build` job as entry point
    machine: true # run the steps with Docker

    environment: # environment variables for the build itself
      TEST_RESULTS: /tmp/test-results # path to where test results will be saved

    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run: mkdir -p $TEST_RESULTS # create the test results directory

      - run:
          name: Build Docker Image
          command: |
            docker build -t hellow-world:latest .
            docker save -o /tmp/test-results/hellow-world.tar hellow-world:latest

      - store_artifacts: # upload test summary for display in Artifacts
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # upload test results for display in Test Summary
          path: /tmp/test-results

  approval:
    type: approval
    machine: true # run the steps with Docker
    requires:
      - build
    steps: # steps that comprise the `build` job
      - checkout # check out source code to working directory
      - run:
          name: Save Docker Image
          command: |
            docker save -o /tmp/test-results/hellow-world.tar hellow-world:latest


workflows:
  version: 2
  build-workflow:
    jobs:
      - test
      - build
      - approval
